### ISSUE TITLE
run RiboSplitter using non SplAdder input

### ISSUE THREAD

**Issue by ls233** [R-Najjar/RiboSplitter#1]
Thanks for the useful tool!

While the publication suggests that RiboSplitter can be run using non SplAdder input (PSI table), a quick look in the source code suggests that the current implementation assumes that the input is meant to be coming specifically from SplAdder. 

Could you please provide instructions/example for how'd I run RiboSplitter using PSI table generated by applications other than SplAdder.

**Comment by R-Najjar** [comment]
You will need to format the output to match the expected format of the two input datasets as described in the manuscript and in Note 2 in the ReadMe.
What tool are you using? You can write a new function that does the reformatting, I'd be happy to help and review the code

**Comment by R-Najjar** [comment]
I will close this, let me know if you have more questions

**Comment by ls233** [comment]
NP, at this point I'm opting in for actually generating the input
using SplAdder. If this isn't going to work (my datasets are in
thousands of samples), will circle back with you for working out a
conversion of the input from SUPPA/rMATS .

**Comment by R-Najjar** [comment]
Ok, hope it works well
