### ISSUE TITLE
relationships between the "ensembl_version" and the "ref_fasta" arguments

### ISSUE THREAD

**Issue by ls233** [R-Najjar/RiboSplitter#3]
Hi Rayan,

I'm puzzled by the relationships between the "ensembl_version" and the "ref_fasta" arguments. Does the tools require the reference genome fasta to come from ensembl? 

If not, and say I ran SplAdder using the reference genome fasta from genecode (for example "hg38_gencode_v30"), how do I figure whic value needs to be provided for the "ensembl_version" parameter?

I'm really excited about being able to use your tool and I'm looking forward to hear from you!

Thanks,
German

**Comment by R-Najjar** [comment]
Hi German,
You can use gencode. Gencode and ensembl release corresponding versions. For example ensembl 111 corresponds to gencode 45. A quick search can get this information, or on the ensembl website https://useast.ensembl.org/Homo_sapiens/Info/Annotation 

Glad you're finding the tool useful
