### ISSUE TITLE
non-model system with multi-level groups?

### ISSUE THREAD

**Issue by kate-stankiewicz** [R-Najjar/RiboSplitter#4]
Hello, 

This tool looks really great! I would love to use it, however, I see that it asks for "ensembl_version: Make sure this corresponds to the reference genome you use." I am using a non-model species that does not have an ensembl version (genome was assembled in house). Is it possible to still use RiboSplitter somehow? When I exclude the ensembl version I receive an error (though I am not sure if it is related to excluding the ensembl or not). I receive this error:

`Error in collect():
! Failed to collect lazy table.
Caused by error in db_collect():
! Arguments in ... must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Run rlang::last_trace() to see where the error occurred.` 

Here is the code I used:

`de_events=ribosplitter(isoforms_df=isoforms, details_df=details,min_disease=10, min_control=10, sd_cutoff=0.05, dir='~/ribosplitter_res', ref_fasta='~/genomes/scaffolds.fa', q_cutoff=0.05)`

Also, I have labeled my samples as "disease" and "control", per the instructions. However, that isn't actually a great classification for them. This is a multi-level design with nested groups (so say treatmeants low, med, and high, then timepoints 1-5). Is it possible to have RiboSplitter recognize a complex design like this?

Many thanks!

**Comment by R-Najjar** [comment]
Hi Kate,
Thanks for your interest. 
Are you sure it's not in Ensembl? you can double check here https://www.bioconductor.org/packages/release/bioc/vignettes/biomaRt/inst/doc/accessing_ensembl.html under step 2. If it is, or if you can find a way to create one, then I can help you incorporate it into RiboSplitter. 
This ensembl database has information on genes, transcripts, positions of their exons, and their protein amino acid sequences.

As for the design, RiboSplitter can only compare two groups, I would compare the two groups that you think would have the biggest difference, then you can take the identified statistically different alternative splicing events with a certain magnitude of difference, and plot their PSI over all the time points and groups to see if there's a dose response.

**Comment by kate-stankiewicz** [comment]
Hi Rayan,

Thanks for the quick reply! I am sure it is not there--I just double checked. It is a genome assembly for a species that is not yet published. I'll see if it is possible to create one. 

That makes sense regarding the two-group comparison. 

Thanks!

**Comment by kate-stankiewicz** [comment]
Hi Rayan,

An update: I don't think it's possible to add a new species to biomart, as new species are added according to community interest. However, I have files that have the information you mentioned for my study species (genes, transcripts, positions of their exons, and their protein amino acid sequences). I'm guessing it is still not possible to use RiboSplitter using non-ensembl genome annotation files, though? From a quick look at the source code it seems there would have to be major changes to add flexibility for non-ensembl species.

**Comment by R-Najjar** [comment]
Hi Kate,
It will require some work but I think it's doable. I think there are only a couple of places where I use Ensembl in the translation and differential testing parts of the pipeline, and a few other times for generating the figures. If you'd like to edit the pipeline, let me know and I can help.

**Comment by kate-stankiewicz** [comment]
Thanks Rayan! I'll reach back out if I do end up going that route!
